# Generated by Django 3.2.17 on 2023-03-15 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paynrentapp', '0004_vechicle'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vechicle',
        ),
        migrations.RenameField(
            model_name='subcategory',
            old_name='icon',
            new_name='subicon',
        ),
    ]
