# Generated by Django 3.2.17 on 2023-03-15 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paynrentapp', '0005_auto_20230315_2329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='categoryid',
            field=models.CharField(default='', max_length=200),
        ),
    ]
