# Generated by Django 3.2.17 on 2023-03-16 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paynrentapp', '0009_rename_subicon_subcategory_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryid', models.CharField(default='', max_length=200)),
                ('subcategoryid', models.CharField(default='', max_length=200)),
                ('companyname', models.CharField(default='', max_length=200)),
                ('subcategoryname', models.CharField(default='', max_length=200)),
                ('modelyear', models.CharField(default='', max_length=200)),
                ('price', models.CharField(default='', max_length=200)),
                ('insured', models.CharField(default='', max_length=200)),
                ('registrationno', models.CharField(default='', max_length=200)),
                ('ownername', models.CharField(default='', max_length=200)),
                ('mobileno', models.CharField(default='', max_length=200)),
                ('color', models.CharField(default='', max_length=200)),
                ('fueltype', models.CharField(default='', max_length=200)),
                ('noofseats', models.CharField(default='', max_length=200)),
                ('transmissiontype', models.CharField(default='', max_length=200)),
                ('picture', models.ImageField(upload_to='static/')),
            ],
        ),
    ]
