# Generated by Django 3.2.17 on 2023-03-17 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paynrentapp', '0010_vehicles'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicles',
            name='varient',
            field=models.CharField(default='', max_length=200),
        ),
    ]
