# Generated by Django 3.2.17 on 2023-03-26 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paynrentapp', '0012_rename_varient_vehicles_variant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicles',
            name='subcategoryname',
        ),
    ]
