# Generated by Django 3.2.17 on 2023-03-26 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paynrentapp', '0013_remove_vehicles_subcategoryname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adminname', models.CharField(default='', max_length=200)),
                ('mobileno', models.CharField(default='', max_length=200)),
                ('emailid', models.CharField(default='', max_length=200)),
                ('password', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
