# Generated by Django 3.2.17 on 2023-06-19 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paynrentapp', '0014_administrator'),
    ]

    operations = [
        migrations.CreateModel(
            name='customersubmit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customername', models.CharField(default='', max_length=200)),
                ('mobileno', models.CharField(default='', max_length=200)),
                ('emailid', models.CharField(default='', max_length=200)),
                ('selectedvehcile', models.CharField(default='', max_length=200)),
                ('startdate', models.CharField(default='', max_length=200)),
                ('enddate', models.CharField(default='', max_length=200)),
                ('amount', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
