# Generated by Django 4.2.3 on 2023-07-21 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paynrentapp', '0015_customersubmit'),
    ]

    operations = [
        migrations.DeleteModel(
            name='customersubmit',
        ),
    ]
